[versions]
kotlin = "1.5.31"

[libraries]
android-gradle = "com.android.tools.build:gradle:7.0.3"
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
androidx-appcompat = "androidx.appcompat:appcompat:1.3.1"
androidx-preference-ktx = "androidx.preference:preference-ktx:1.1.1"
androidx-navigation-ui-ktx = "androidx.navigation:navigation-ui-ktx:2.3.5"
androidx-navigation-fragment-ktx = "androidx.navigation:navigation-fragment-ktx:2.3.5"
google-material = "com.google.android.material:material:1.4.0"

free-reflection = "me.weishu:free_reflection:3.0.1"
viewbinding-property-delegate = "com.github.kirich1409:viewbindingpropertydelegate-noreflection:1.4.7"

squareup-leakcanary = "com.squareup.leakcanary:leakcanary-android:2.7"

junit = "junit:junit:4.13.2"
androidx-junit = "androidx.test.ext:junit:1.1.3"
androidx-expresso-core = "androidx.test.espresso:espresso-core:3.4.0"

[bundles]
classpath = ["android-gradle", "kotlin-gradle"]
androidx-navigation = ["androidx-navigation-ui-ktx", "androidx-navigation-fragment-ktx"]
androidx-test = ["androidx-junit", "androidx-expresso-core"]
